### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by Leonos** [Bodmer/DarkSkyWeather#10]
@bodmer, 
First off: this is not really an issue. If you remember we talked over @squix78's streaming parser repository about my perceived lack of clear examples for his json parser. 

In your response you helped me to get on the right track but because WUnderground postponed their December 31 API cancellation, I hadn't really started looking seriously into it until last weekend. 

And I can't thank you enough for your efforts providing the Apixu examples. I managed to convert your code so it enables me to get the History data as well (needed for moon phase and moon illumination). To get what I got from WU until now, I would need to get Apixu's Forecast **and** History jsons (for current weather and sun/moon data), combined with DarkSky's Forecast json for the longer descriptions ("Clear throughout the day, Light rain on Sunday, with high temperatures falling to 15°C on Tuesday"). I am now in the process to combine all 3 in a single .h/.cpp to be used in my clock program. I wouldn't have been able to do that without your work!! Finally this whole parsing procedure is clear to me.

But I understand this place is not really meant for random forum chat like I am doing now, so please forgive me, but to make it more relevant to this Issues place, I wondered the following. 

For the ESP32 you got the certificate from somewhere and I tried to find out which one you took but I was unable to get the same as the one you included. Anyway, just to say I found out a little later that this is a moot point since if the code 
`client.setCACert(dsw_ca_cert);`
is commented out, everything still works as before. So it seems that whole certificate part is not needed, and that is a good thing since then there's also no expiration date you would have to deal with...

**Comment by Bodmer** [comment]
Library updated to ignore certificate confirmation and hence avoid expiry.
