### ISSUE TITLE
Example DarkSky Weather ILI9341

### ISSUE THREAD

**Issue by Nelson666** [Bodmer/DarkSkyWeather#13]
Hello,

I‘ve tested the example DarkSky Weather with my ILI9341 and an NodeMCU V3. It works, but a issue with the font drawing is there. It draws the font from SPIFFS but it draws another little font (the real font overlaps the little font). Can you help me?

Edit: A Picture for clearness. 
https://www.bilder-upload.eu/bild-80537b-1549908731.jpeg.html

**Comment by Bodmer** [comment]
Sorry! This is my fault! I uploaded a version of the library recently that contained a bug. I updated the library quite quickly but in the meantime I expect you downloaded the rogue copy...

The library is now at version 1.4.4.  If updating the library does not fix it then do let me know and I will investigate further.

**Comment by Nelson666** [comment]
Now it works correctly. 
Thanks, for the nice Project.
