### ISSUE TITLE
Data_Point_Set.h error

### ISSUE THREAD

**Issue by Dancopy** [Bodmer/DarkSkyWeather#14]
Hi Bodmer
I'm trying to load this sketch but it's showing this error:

Arduino: 1.8.5 (Windows 10), Card: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, 4M (in SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch,

Compilation options changed, recompiling all
59: 0: C: \ Users \ Daniel \ Downloads \ DarkSkyWeather-master \ examples \ TFT_eSPI_weather \ TFT_eSPI_weather.ino:

: 20: 28: fatal error: Data_Point_Set.h: No such file or directory C: \ Users \ Daniel \ Documents \ Arduino \ libraries \ DarkSkyWeather / DarkSkyWeather.h:

  #include "Data_Point_Set.h"
                             ^
compilation terminated.

exit status 1
Compiling error for NodeMCU 1.0 (ESP-12E Module)

ESP8266 v2.5.0

**Comment by Bodmer** [comment]
The header file [exists](https://github.com/Bodmer/DarkSkyWeather/blob/master/Data_Point_Set.h) so should be found. Check your library setup.

**Comment by Dancopy** [comment]
Arduino: 1.8.5 (Windows 10), Placa:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Opções de compilação alteradas, recompilando tudo
AVISO: a biblioteca Timezone-master alega rodar em arquitetura(s) (avr) e pode ser incompatível com sua placa atual, que roda em arquitetura(s) (esp8266).
In file included from C:\Users\Daniel\Documents\Arduino\libraries\DarkSkyWeather/DarkSkyWeather.h:20:0,

                 from C:\Users\Daniel\Downloads\DarkSkyWeather-master\examples\TFT_eSPI_weather\TFT_eSPI_weather.ino:59:

C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:43:17: error: 'MAX_MINUTES' was not declared in this scope

   uint32_t time[MAX_MINUTES] = { 0 }; // maybe store as a minute start time + minute
                 ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:45:28: error: 'MAX_MINUTES' was not declared in this scope

   float    precipIntensity[MAX_MINUTES] = { 0 }; // Q: what is the value range for this?
                            ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:46:30: error: 'MAX_MINUTES' was not declared in this scope

   uint8_t  precipProbability[MAX_MINUTES] = { 0 };// float 0.0 to 1.0 -> 0-100%
                              ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:57:20: error: 'MAX_HOURS' was not declared in this scope

   String   summary[MAX_HOURS];
                    ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:58:17: error: 'MAX_HOURS' was not declared in this scope

   uint32_t time[MAX_HOURS] = { 0 };
                 ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:59:28: error: 'MAX_HOURS' was not declared in this scope

   float    precipIntensity[MAX_HOURS] = { 0 };
                            ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:60:23: error: 'MAX_HOURS' was not declared in this scope

   uint8_t  precipType[MAX_HOURS] = { NO_VALUE };
                       ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:61:30: error: 'MAX_HOURS' was not declared in this scope

   uint8_t  precipProbability[MAX_HOURS] = { 0 };
                              ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:62:31: error: 'MAX_HOURS' was not declared in this scope

   float    precipAccumulation[MAX_HOURS] = { 0 };
                               ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:63:24: error: 'MAX_HOURS' was not declared in this scope

   float    temperature[MAX_HOURS] = { 0 };
                        ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:64:21: error: 'MAX_HOURS' was not declared in this scope

   float    pressure[MAX_HOURS] = { 0 };
                     ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:65:23: error: 'MAX_HOURS' was not declared in this scope

   uint8_t  cloudCover[MAX_HOURS] = { 0 };
                       ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:76:20: error: 'MAX_DAYS' was not declared in this scope

   String   summary[MAX_DAYS];
                    ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:77:17: error: 'MAX_DAYS' was not declared in this scope

   uint32_t time[MAX_DAYS] = { 0 };
                 ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:78:17: error: 'MAX_DAYS' was not declared in this scope

   uint8_t  icon[MAX_DAYS] = { 0 };
                 ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:79:24: error: 'MAX_DAYS' was not declared in this scope

   uint32_t sunriseTime[MAX_DAYS] = { 0 };
                        ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:80:23: error: 'MAX_DAYS' was not declared in this scope

   uint32_t sunsetTime[MAX_DAYS] = { 0 };
                       ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:81:22: error: 'MAX_DAYS' was not declared in this scope

   uint8_t  moonPhase[MAX_DAYS] = { 0 };
                      ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:82:28: error: 'MAX_DAYS' was not declared in this scope

   float    precipIntensity[MAX_DAYS] = { 0 };
                            ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:83:30: error: 'MAX_DAYS' was not declared in this scope

   uint8_t  precipProbability[MAX_DAYS] = { 0 };
                              ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:84:23: error: 'MAX_DAYS' was not declared in this scope

   uint8_t  precipType[MAX_DAYS] = { NO_VALUE };
                       ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:85:31: error: 'MAX_DAYS' was not declared in this scope

   float    precipAccumulation[MAX_DAYS] = { 0 };
                               ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:86:28: error: 'MAX_DAYS' was not declared in this scope

   float    temperatureHigh[MAX_DAYS] = { 0 };
                            ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:87:27: error: 'MAX_DAYS' was not declared in this scope

   float    temperatureLow[MAX_DAYS] = { 0 };
                           ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:88:21: error: 'MAX_DAYS' was not declared in this scope

   uint8_t  humidity[MAX_DAYS] = { 0 };
                     ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:89:21: error: 'MAX_DAYS' was not declared in this scope

   float    pressure[MAX_DAYS] = { 0 };
                     ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:90:22: error: 'MAX_DAYS' was not declared in this scope

   float    windSpeed[MAX_DAYS] = { 0 };
                      ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:91:21: error: 'MAX_DAYS' was not declared in this scope

   float    windGust[MAX_DAYS] = { 0 };
                     ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:92:24: error: 'MAX_DAYS' was not declared in this scope

   uint16_t windBearing[MAX_DAYS] = { 0 };
                        ^
C:\Users\Daniel\Documents\Arduino\libraries\Data_Point_Set/Data_Point_Set.h:93:23: error: 'MAX_DAYS' was not declared in this scope

   uint8_t  cloudCover[MAX_DAYS] = { 0 };
                       ^
C:\Users\Daniel\Downloads\DarkSkyWeather-master\examples\TFT_eSPI_weather\TFT_eSPI_weather.ino: In function 'void drawForecastDetail(uint16_t, uint16_t, uint8_t)':

TFT_eSPI_weather:428: error: 'MAX_DAYS' was not declared in this scope

   if (dayIndex >= MAX_DAYS) return;
                   ^
TFT_eSPI_weather:430: error: 'DSW_daily' has no member named 'time'

   String day  = dayShortStr(weekday(TIMEZONE.toLocal(daily->time[dayIndex], &tz1_Code)));
                                                             ^
TFT_eSPI_weather:441: error: 'DSW_daily' has no member named 'temperatureHigh'

   String highTemp = String(daily->temperatureHigh[dayIndex], 0);
                                   ^
TFT_eSPI_weather:442: error: 'DSW_daily' has no member named 'temperatureLow'

   String lowTemp  = String(daily->temperatureLow[dayIndex], 0);
                                   ^
TFT_eSPI_weather:445: error: 'DSW_daily' has no member named 'icon'

   String weatherIcon = getMeteoconIcon(daily->icon[dayIndex]);
                                               ^
C:\Users\Daniel\Downloads\DarkSkyWeather-master\examples\TFT_eSPI_weather\TFT_eSPI_weather.ino: In function 'void drawAstronomy()':

TFT_eSPI_weather:468: error: 'DSW_daily' has no member named 'moonPhase'

   uint8_t moonIndex = (uint8_t)(((float)daily->moonPhase[dayIndex] + 6.25) / 12.5);
                                                ^
TFT_eSPI_weather:472: error: 'DSW_daily' has no member named 'moonPhase'

   uint8_t moonAgeImage = (24.0 * daily->moonPhase[dayIndex]) / 100;
                                         ^
TFT_eSPI_weather:485: error: 'DSW_daily' has no member named 'sunriseTime'

   String rising = strTime(daily->sunriseTime[dayIndex]) + " ";
                                  ^
TFT_eSPI_weather:489: error: 'DSW_daily' has no member named 'sunsetTime'

   String setting = strTime(daily->sunsetTime[dayIndex]) + " ";
                                   ^
C:\Users\Daniel\Downloads\DarkSkyWeather-master\examples\TFT_eSPI_weather\TFT_eSPI_weather.ino: In function 'void printWeather()':

TFT_eSPI_weather:644: error: 'DSW_daily' has no member named 'summary'

     Serial.print("Day summary   "); Serial.print(i); Serial.print("    : "); Serial.println(daily->summary[i]);
                                                                                                    ^
TFT_eSPI_weather:645: error: 'DSW_daily' has no member named 'time'

     Serial.print("time               : "); Serial.println(strDate(daily->time[i]));
                                                                          ^
TFT_eSPI_weather:646: error: 'DSW_daily' has no member named 'icon'

     Serial.print("icon               : "); Serial.println(daily->icon[i]);
                                                                  ^
TFT_eSPI_weather:647: error: 'DSW_daily' has no member named 'sunriseTime'

     Serial.print("sunriseTime        : "); Serial.println(strDate(daily->sunriseTime[i]));
                                                                          ^
TFT_eSPI_weather:648: error: 'DSW_daily' has no member named 'sunsetTime'

     Serial.print("sunsetTime         : "); Serial.println(strDate(daily->sunsetTime[i]));
                                                                          ^
TFT_eSPI_weather:649: error: 'DSW_daily' has no member named 'moonPhase'

     Serial.print("Moon phase         : "); Serial.println(daily->moonPhase[i]);
                                                                  ^
TFT_eSPI_weather:650: error: 'DSW_daily' has no member named 'temperatureHigh'

     Serial.print("temperatureHigh    : "); Serial.println(daily->temperatureHigh[i]);
                                                                  ^
TFT_eSPI_weather:651: error: 'DSW_daily' has no member named 'temperatureLow'

     Serial.print("temperatureLow     : "); Serial.println(daily->temperatureLow[i]);
                                                                  ^
exit status 1
'MAX_DAYS' was not declared in this scope


NOTES: DarkSkyWeather.cpp and DarkSkyWeather.h
            are installed in the DarkSkyWeather libraries directory, as well as Data_Point_Set.
            All the libraries are installed.
            Timezone downloaded from anywhere on the internet.

**Comment by Bodmer** [comment]
It looks like you have tried to fix the problem by moving the header file to a new folder, this should not be neccessary.

The new problem is that [User_Setup.h must be loaded first](https://github.com/Bodmer/DarkSkyWeather/blob/master/DarkSkyWeather.h#L19) as that defines the missing #defines.

There is something wrong with your IDE setup or operating environment, these problems should not occur! I suggest you load the latest IDE and see if that corrects your setup, it is not an issue with the library.

**Comment by Dancopy** [comment]
Hi Bodmer! Be patient with me, I'm lost but I'd love to use your sketch.

In the 'DarkSkyWeather-master' folder has the examples folder with 'My_DarkSkyWeather_Test' and 'TFT_eSPI_weather' inside. I'm thinking I should use the 'TFT_eSPI_weather' sketch.

Outside these folders, you have 4 main files: DarkSkyWeather.cpp - DarkSkyWeather.h - Data_Point_Set.h and User_Setup.h. Where should I put these four files?

Sorry for my ignorance on the subject; if you want to answer me, I'll be very grateful.

PS. What should I do with the User_Setup.h file?
PS2. I forgot something else: should the 'data' folder be loaded into the SPIFFS of esp?

Thank you,
Daniel

**Comment by Bodmer** [comment]
OK, I am happy to help. It took me a while to realize what you have done. It appears you are trying to pull the library files into a sketch. That is not the way to run library examples.

DarkSkyWeather is not an example itself, it is a library. The library, like other Arduino libraries, contains the examples.

Download the library, place it in the Arduino libraries folder. Then after that run the IDE, look in the IDE File->Examples menu for the DarkSkyWeather library menu item and load the example from that IDE menu. It will then compile OK. Edit the settings of the example as needed.

**Comment by Dancopy** [comment]
Big man! Super!
I did not think you had done your beautiful and excellent program as Library, to install directly into the Arduino IDE. I thought it was all separate. If you do not mind, I have two more questions:

1) I tried to correct my time (Brazil), which is -3 hours and I thought it was on line 303; String timeNow = "";
Ex. 20:40 is showing 23:40.

2) My language is Portuguese, so, for example: FRI, for me it should be SEX; SAT should be SAB; SUN should be DOM; MON must be SEG, etc.

Where should I change these two points I mentioned above?

I admire and recognize your beautiful and hard work!

Once again, thank you very much.

**Comment by Dancopy** [comment]
I would stay here again, Bodmer! (perhaps bothering you)
I had not looked and it seems to be the correction of the time zone in Brazil, right?

So, as in the example below, how should it be for Brazil?

// Zone reference "usCT" US Central Time Zone (Chicago, Houston)
TimeChangeRule usCDT = {"CDT", Second, dowSunday, Mar, 2, -300};
TimeChangeRule usCST = {"CST", First, dowSunday, Nov, 2, -360};
Timezone usCT(usCDT, usCST);

Should I add 3 more lines of these?
Since, in Brazil, the Standard Time is -3 and the Daylight Saving Time is -2;

And how should these initials be:

TimeChangeRule usCDT = {"CDT", ...........
TimeChangeRule usCST = {"CST", ...........

Thank you friend,

**Comment by Bodmer** [comment]
The link to the language codes document [is here](https://github.com/Bodmer/DarkSkyWeather/blob/master/examples/TFT_eSPI_weather/All_Settings.h#L40-L41). So you need to change "en" to "pt".

The information for the timezone and Daylight Saving corrections are detailed in[ this link](https://github.com/Bodmer/DarkSkyWeather/blob/master/examples/TFT_eSPI_weather/NTP_Time.h#L11).

The correction is in minutes, so in your case the correction will be -180 and -120

The default selection in the All_Settings.h tab is UK as noted[ here](https://github.com/Bodmer/DarkSkyWeather/blob/master/examples/TFT_eSPI_weather/NTP_Time.h#L55).  If you wish to use usCT then you change the line [here](https://github.com/Bodmer/DarkSkyWeather/blob/master/examples/TFT_eSPI_weather/All_Settings.h#L27) to:
```
#define TIMEZONE usCT 
```

**Comment by Dancopy** [comment]
Hi Bodmer! I'm writing to you again to let you know.

1) In 'Daylight Saving Corrections' I did so:

// Zone reference "BR" Brazil (Sta Catarina, São Paulo)
TimeChangeRule BRST = {"BRST", Second, Sun, Oct, 0, -120}; // Brazilian Daylight Time (Daylight Saving Time)
TimeChangeRule BRT = {"BRT", Second, Sun, Feb, 0, -180}; // Standard time
Timezone BR (BRT, BRST);

2) Where was #define TIMEZONE UK, I left:
                      #define TIMEZONE BR // Brazil

3) Here I left: const String language = "pt";

And everything is working, except for the days of the week: SUN, MON, TUE, etc., even though it has gone to ..... = "pt"; are appearing in English.
Hope that the 'Dark Sky API' site always makes available the free APIs!

I really liked the look (graphics) you made, but I'd really like to use it on a much larger screen, like 5-inch, like this: RA8875;

Again, thank you very much to you.

Daniel

**Comment by Bodmer** [comment]
Hi Daniel,

Great to hear you have made progress and have the time correction sorted.

The question re. short strings for the day of the week is a good one.  This is handled by the Arduino "Time" library but we can substitute the short Portuguese day names. Would they be: SEG TER QUA QUI SEX SAB DOM ? Note the existing font does not have "Á" for SÁB but it could be added easily.

**Comment by Bodmer** [comment]
I have made changes to the TFT_eSPI example in the library. TFT_eSPI_weather.ino and All_Settings.h have changed so you only need to copy these 2 files over from the new zip download file.

You can now define the day of week labels and other labels in you language within the examples All_Settings.h file.

**Comment by Dancopy** [comment]
Hi my friend! Great! Note 1000 for you!
The "Á" for SABADO or SAB abbreviated (in Brazilian Portuguese) does not need the accent.
Now I will only wait to get my Display 3.5 "ILI9488 that I bought through ebay to connect to Nodemcu.
I can only say: thank you very much and may God bless you
