### ISSUE TITLE
Problem with ST7735 Screen - Size / resolution

### ISSUE THREAD

**Issue by 68gt500** [Bodmer/DarkSkyWeather#15]
I have the TFT example running, but some info & grafics is out of bounds.

My ST7735  160 x 128 works fine with all the examples of your TFT_eSPI library.  

Running an ESP32 Dev Module V1 and current Arduino IDE.

Any help appreciated.

**Comment by Bodmer** [comment]
The TFT example is designed for a 320 x 240 pixel screen so is not suitable for a smaller display.

The "My_DarkSkyWeather_Test" example sends the data to the serial port, but could be a starting point to create a weather display for a smaller screen.

**Comment by 68gt500** [comment]
Thanks, that is what I feared ;-)
I´ll close the issue
