### ISSUE TITLE
UDP TIME localPort = 2390

### ISSUE THREAD

**Issue by KuhnDaniel** [Bodmer/DarkSkyWeather#16]
Hello Mr. Bodmer, thank you for the module! I had problems with the NTP query with my ESP32. Have now changed the internal port from 2390 to 1230 in NTP_Time.h and now the update is 100% constant. Granted, I have an IPFIRE here which regulates my network traffic and Ubiquiti WLAN AC in use. Since disturbed probably the port 2390? Sunny greetings from Germany, Daniel

**Comment by Bodmer** [comment]
Thanks for the tip. This issue seems specific to your setup but may help others.
