### ISSUE TITLE
In member function 'bool DS_Weather::parseRequest(String)':

### ISSUE THREAD

**Issue by darox** [Bodmer/DarkSkyWeather#19]
While compiling I'm facing the following errors:

C:\Users\Dario\Documents\Arduino\libraries\DarkSkyWeather-master\DarkSkyWeather.cpp: In member function 'bool DS_Weather::parseRequest(String)':

C:\Users\Dario\Documents\Arduino\libraries\DarkSkyWeather-master\DarkSkyWeather.cpp:210:5: error: 'BearSSL' has not been declared

     BearSSL::WiFiClientSecure client;

     ^

C:\Users\Dario\Documents\Arduino\libraries\DarkSkyWeather-master\DarkSkyWeather.cpp:210:31: error: expected ';' before 'client'

     BearSSL::WiFiClientSecure client;

                               ^

C:\Users\Dario\Documents\Arduino\libraries\DarkSkyWeather-master\DarkSkyWeather.cpp:217:7: error: 'client' was not declared in this scope

       client.setInsecure();

       ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

How can this be resolved?

**Comment by darox** [comment]
I just updated the board sw and now it works.

**Comment by Bodmer** [comment]
BearSSL is supposed to be more memory efficient so a user asked me to add the capability to use it. Unfortunately this does mean the latest board package is needed.

Glad to hear you have fixed it and thanks for letting me know.

**Comment by darox** [comment]
@Bodmer May you share the correct wiring for the TFT_eSPI_weather ? And do I have to resolve this error:
Font file fonts/NotoSansBold15 not found!

Thanks!

**Comment by Bodmer** [comment]
I can tell you but I need to know what hardware you have.

The error must be fixed by uploading the file to SPIFFS.

**Comment by darox** [comment]
I have a nodemcu ESP8266 12E.

**Comment by Bodmer** [comment]
Which TFT are you using and what are the pin signal names for the TFT?

**Comment by darox** [comment]
I'm using this one CHF 5.08  16%OFF | 2,8 "240x320 SPI TFT LCD Serial Port Modul Mit PCB Adapter Micro SD ILI9341 5 v/ 3,3 v 2,8 zoll LED Display Für 5110 Interface
https://s.click.aliexpress.com/e/bOFMsdtA

**Comment by Bodmer** [comment]
OK, in that case you can use the library with no changes if you wire the NodeMCU to the display [like this](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup.h#L98-L106).

**Comment by darox** [comment]
@Bodmer That's what i did, please check the link, it's wrongly displayed: https://imgur.com/a/xJ7uhsT

**Comment by Bodmer** [comment]
Looks like you have not uploaded the icons and fonts to SPIFFS!

Read the comments [here](https://github.com/Bodmer/DarkSkyWeather/blob/master/examples/TFT_eSPI_weather/All_Settings.h#L11).

**Comment by darox** [comment]
@Bodmer Now I'm getting the following error:
SPIFFS Not Defined for NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200

**Comment by Bodmer** [comment]
You need to use the Tools Flash Size menu option to [set SPIFFS to 2 Mbytes as noted here](https://github.com/Bodmer/DarkSkyWeather/blob/master/examples/TFT_eSPI_weather/All_Settings.h#L8).

There are tutorials on SPIFFS on the internet that you may find useful.

**Comment by darox** [comment]
@Bodmer It worked, many thanks for the great support!

**Comment by Bodmer** [comment]
Glad to hear you have it working!
