### ISSUE TITLE
won't compile

### ISSUE THREAD

**Issue by zpowellman** [Bodmer/DarkSkyWeather#20]
Getting this issue at compile time.  Did I miss a note somewhere?  Using 1.8.9 of IDE.
Flash of graphics to spiffs worked fine.  Not worried about warning.

WARNING: library Timezone claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (esp8266) architecture(s).
In file included from C:\Users\Dan\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266/pgmspace.h:7:0,

                 from C:\Users\Dan\Documents\Arduino\libraries\TFT_eSPI-master/Fonts/glcdfont.c:6,

                 from C:\Users\Dan\Documents\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.h:60,

                 from C:\Users\Dan\Documents\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:16:

C:\Users\Dan\Documents\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'virtual int16_t TFT_eSPI::drawChar(unsigned int, int, int, int)':

C:\Users\Dan\Documents\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:3920:84: error: invalid conversion from 'uint32_t {aka unsigned int}' to 'const void*' [-fpermissive]

       flash_address = pgm_read_dword( pgm_read_dword( &(fontdata[font].chartbl ) ) + uniCode*sizeof(void *) );

                                                                                    ^

C:\Users\Dan\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:114:57: note: in definition of macro 'pgm_read_dword'

     #define pgm_read_dword(a)  pgm_read_dword_unaligned(a)

                                                         ^

C:\Users\Dan\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:85:72: error:   initializing argument 1 of 'uint32_t pgm_read_dword_unaligned(const void*)' [-fpermissive]

 __attribute__((optimize("-O3"), always_inline)) static inline uint32_t pgm_read_dword_unaligned(const void *addr) {

                                                                        ^

C:\Users\Dan\Documents\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp: In member function 'virtual int16_t TFT_eSprite::drawChar(unsigned int, int, int, int)':

C:\Users\Dan\Documents\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp:1342:84: error: invalid conversion from 'uint32_t {aka unsigned int}' to 'const void*' [-fpermissive]

       flash_address = pgm_read_dword( pgm_read_dword( &(fontdata[font].chartbl ) ) + uniCode*sizeof(void *) );

                                                                                    ^

C:\Users\Dan\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:114:57: note: in definition of macro 'pgm_read_dword'

     #define pgm_read_dword(a)  pgm_read_dword_unaligned(a)

                                                         ^

C:\Users\Dan\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:85:72: error:   initializing argument 1 of 'uint32_t pgm_read_dword_unaligned(const void*)' [-fpermissive]

 __attribute__((optimize("-O3"), always_inline)) static inline uint32_t pgm_read_dword_unaligned(const void *addr) {

                                                                        ^

exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

**Comment by Bodmer** [comment]
Use the latest version of TFT_eSPI. 
The ESP8277 2.5.2 is sensitive to type now. The latest TFT_eSPI has been updated to handle this.
