### ISSUE TITLE
Occasional Crash and Reboot

### ISSUE THREAD

**Issue by jlmyra** [Bodmer/DarkSkyWeather#21]
First thanks for sharing your routine. Well done!
i have my Wemos D1 mini running your code and scrolling it out on a 2 line lcd. It accesses DarkSky every 5 minutes.  The serial monitor shows that it crashes and reboots occasionally when accessing Dark Sky. The error message is below -

Requesting weather information from DarkSky.net... 

Panic /Users/JLM/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/cores/esp8266/core_esp8266_main.cpp:134 loop_task

>>>stack>>>

ctx: sys
sp: 3fffed90 end: 3fffffb0 offset: 01b0
3fffef40:  00000000 3fffdad0 3ffefe38 40209edd  
.
.
.

Is this an expected behavior accessing DarkSky or do I need to dig deeper into my code?

Thanks.

**Comment by Bodmer** [comment]
Crashes can be tricky to track down. A common cause of a restart is a watchdog time-out. To stop this loops that wait for something to happen should iinclude a yield(); or delay(0); statement.

If your LCD is I2C based theb it could be the case that the I2C library got stuck waiting for an ACK on the bus. Without knowing what your code does, this is just a guess.

I would run just the example code (My_DarkSkyWeather_Test) with your APID and see if that reboots occasionally on your setup. If it runs OK then add in code bit by bit and see what addition triggers a crash.

**Comment by jlmyra** [comment]
Thanks! I have narrowed the rebooting to memory issues caused by my misuse of Strings. I parse the output of your code and build a line of text using Strings that scrolls on an LCD display. Once I figure out how to convert to character arrays I'm sure that will take care of the random reboots.
