### ISSUE TITLE
feature request - minutely data

### ISSUE THREAD

**Issue by smokiem** [Bodmer/DarkSkyWeather#22]
Would you please consider a feature request to extract the minutely forecast?
Your library will show DSW_current, DSW_hourly and DSW_daily, I'm hoping you could add DSW_minutely... I'm making a simple ticker and want to show the forecast for the next hour to know if I should leave the laundry drying outside, or if I should light the BBQ.

**Comment by Bodmer** [comment]
I will look at this for you but it will be a few weeks before I have time due to other work demands.

**Comment by smokiem** [comment]
Much appreciated :) 
In the meantime I've set up a Raspberry Pi to do the json extraction, and am now working to make the ESP32 retrieve a simple one-liner using ftp. This will work for me at home, but I'd love a slicker solution to deploy in a few other locations!

**Comment by Bodmer** [comment]
Feature added and Github updated.

Open issue again if you have any problems with it.

**Comment by smokiem** [comment]
Very happy with this new feature, working perfectly after I deleted and reinstalled the library. Thank you for all your work :)
