### ISSUE TITLE
Compiling error with Esp8266

### ISSUE THREAD

**Issue by Lacybad** [Bodmer/DarkSkyWeather#23]
Hello Bodmer!

First of all i would like to thank you for this very awsome and useful WS.
I have a compiling error with Esp8266 : C:\Program Files (x86)\Arduino\libraries\DarkSkyWeather-master\DarkSkyWeather.cpp:217:7: error: 'client' was not declared in this scope

       client.setInsecure();
I have no idea what is the problem. All my settings, IDE, libraries are up to date. However the Arduino IDE compiler sucessfully compiles it to Esp32.
Any ideas for this issue? Any help is appriciated.

Sincerely:  Lazlo

**Comment by Bodmer** [comment]
Make sure you have the latest board package for the ESP8266 loaded, currently 2.5.2

**Comment by Lacybad** [comment]
Thank you for the response :)
How foolish of me. My version was 2.4.0. After updating no errors occured.

**Comment by Bodmer** [comment]
Glad to help.
