### ISSUE TITLE
Unable to get fonts and icons to load into spiffs

### ISSUE THREAD

**Issue by fixyourlan** [Bodmer/DarkSkyWeather#25]
I have tried many time to upload and get any fonts or icons to upload into spiffs,  the upload part shows all files and folders in the data folder as uploading in Arduino, but then I start the tft_espi_weather sketch it always shows "file not found" 4 times and "Font file fonts/NotoSansBold36" not found 2 times under the directory listing in the serial monitor.  Data displays on my display very small with no icons at all. Any help getting them uploaded would be great.  The sample sketches for all the fonts from the tft_espi samples work ok.  I just cant get your weather fonts and icons to install correctly.  Any one have any ideas on what I'm doing wrong?

**Comment by Bodmer** [comment]
ESP8266 or ESP32?
You need to allocate at least 1.5Mbytes to SPIFFS (I am guessing you have an ESP8266, so set size to 2Mbytes).
After changing the SPIFFS size and uploading the files again you must also recompile and upload the sketch afresh so the the compiled sketch incorporates the correct SPIFFS size information.

**Comment by fixyourlan** [comment]
I tried all sizes and recompiled and uploaded with same result each time 

Jim Bazar

> On Dec 9, 2019, at 11:52 AM, Bodmer <notifications@github.com> wrote:
> 

﻿
ESP8266 or ESP32?
You need to allocate at least 1.5Mbytes to SPIFFS (I am guessing you have an ESP8266, so set size to 2Mbytes).
After changing the SPIFFS size and uploading the files you must also recompile and uplaod the sketch afresh so the the compiled sketch incorporatres the correct SPIFFS size information.

**Comment by Bodmer** [comment]
What version of the Arduino IDE are you using?
Which version of the board package?
Have you loaded a new SPIFFS loader recently?
ESP32 or ESP8266?

**Comment by fixyourlan** [comment]
Using Arduino 1.8.10, with a esp8266 , board ver was 2.6.0.  when I was looking at versions. I had used 2.6.1 last week when it came out and other thing were not working with other scripts so I went back to 2.6.0 and then they were working, so I ignored the next one 2.6.2,  I have now updated to 2.6.2 and now the spiffs work and now have fonts and icons.
BUT,
Now I only get the tomorrows forecast icon, and in the serial port I get the wrong date for the rest of the forecast days.  Read note at start of day 2 summary for details!

SPIFFS files found:
=====================================
  File name               Size
=====================================
/fonts/NotoSansBold15.vlw        10766 bytes
/fonts/NotoSansBold36.vlw        6182 bytes
=====================================

===========================
Drawing file: /splash/DarkSky.jpg
===========================
===============
JPEG image info
===============
Width      :240
Height     :319
Components :1
MCU / row  :15
MCU / col  :20
Scan type  :4
MCU width  :16
MCU height :16
===============

Total render time was    : 456 ms

.

NTP response time was : 40 ms
Time since last sync is: 7.31 s
Received NTP UTC time : 21:09:23
Sending GET request to api.darksky.net...
X-Forecast-API-Calls: 99

Header end found
Parsing JSON

Done in 1682 ms

Weather from Dark Sky

############### Current weather ###############

time               : Dec 9 15:09
summary            : Clear
icon               : 4
temperature        : 78.39
humidity           : 62
pressure           : 1007.90
wind speed         : 4.77
wind dirn          : 128
cloudCover         : 17

###############  Daily weather  ###############

Overall summary     : Light rain tomorrow.

Day summary   0    : Partly cloudy throughout the day.
time               : Dec 9 00:00
icon               : 6
sunriseTime        : Dec 9 07:19
sunsetTime         : Dec 9 17:37
Moon phase         : 43
temperatureHigh    : 79.06
temperatureLow     : 46.26

Day summary   1    : Drizzle in the morning and afternoon.
time               : Dec 10 00:00
icon               : 1
sunriseTime        : Dec 10 07:19
sunsetTime         : Dec 10 17:37
Moon phase         : 46
temperatureHigh    : 50.31
temperatureLow     : 36.04

*************        v  starting here I get backward question marks and a tilde ~ repeating for a long string in the day summary and for the rest of the day summaries after this point, they will not copy and paste into this email. VVVVVVVVV

Day summary   2    :  
time               : Dec 10 07:19
icon               : 196
sunriseTime        : Aug 27 02:28
sunsetTime         : Oct 15 13:22
Moon phase         : 195
temperatureHigh    : 0.00
temperatureLow     : 1022.10

Day summary  3  :  (same backwards question mark and tilde repeating)
time               : Dec 9 07:19
icon               : 3
sunriseTime        : Dec 10 17:37
sunsetTime         : Jun 15 14:40
Moon phase         : 1
temperatureHigh    : 36.04
temperatureLow     : 1010.30

Day summary   4  :  (same backwards question mark and tilde repeating)
time               : Dec 10 07:19
icon               : 196
sunriseTime        : Aug 27 02:28
sunsetTime         : Oct 15 13:22
Moon phase         : 195
temperatureHigh    : 0.00
temperatureLow     : 1022.10


NTP response time was : 65 ms
Time since last sync is: 6.34 s
Received NTP UTC time : 21:09:29
****** end of clip *******

I even increased to 3mb spiffs, but no change.

**Comment by Bodmer** [comment]
Have you made any changes to the sketch such as language?

**Comment by fixyourlan** [comment]
units = "us" and language = "en"

**Comment by Bodmer** [comment]
It looks like the decoded data is corrupted for some reason. I have never seen this before. Do you get good data reported by the example test sketch which spools the output to the serial monitor window.
I will run some tests to see if I can replicatr the issue.

**Comment by fixyourlan** [comment]
the serial output was listed in an reply before showing where the data was corrupt, but here it is again, i don't see this output in the emailed links to this site. only was viable when looking at in on your github site.  data is corrupt after the "Day summary 2"  starts

beginning of serial output ......

Header end found
Parsing JSON

Done in 1682 ms

Weather from Dark Sky

############### Current weather ###############

time : Dec 9 15:09
summary : Clear
icon : 4
temperature : 78.39
humidity : 62
pressure : 1007.90
wind speed : 4.77
wind dirn : 128
cloudCover : 17

############### Daily weather ###############

Overall summary : Light rain tomorrow.

Day summary 0 : Partly cloudy throughout the day.
time : Dec 9 00:00
icon : 6
sunriseTime : Dec 9 07:19
sunsetTime : Dec 9 17:37
Moon phase : 43
temperatureHigh : 79.06
temperatureLow : 46.26

Day summary 1 : Drizzle in the morning and afternoon.
time : Dec 10 00:00
icon : 1
sunriseTime : Dec 10 07:19
sunsetTime : Dec 10 17:37
Moon phase : 46
temperatureHigh : 50.31
temperatureLow : 36.04

************* v starting here I get backward question marks and a tilde ~ repeating for a long string in the day summary and for the rest of the day summaries after this point, they will not copy and paste into this email. VVVVVVVVV

Day summary 2 :
time : Dec 10 07:19
icon : 196
sunriseTime : Aug 27 02:28
sunsetTime : Oct 15 13:22
Moon phase : 195
temperatureHigh : 0.00
temperatureLow : 1022.10

Day summary 3 : (same backwards question mark and tilde repeating)
time : Dec 9 07:19
icon : 3
sunriseTime : Dec 10 17:37
sunsetTime : Jun 15 14:40
Moon phase : 1
temperatureHigh : 36.04
temperatureLow : 1010.30

Day summary 4 : (same backwards question mark and tilde repeating)
time : Dec 10 07:19
icon : 196
sunriseTime : Aug 27 02:28
sunsetTime : Oct 15 13:22
Moon phase : 195
temperatureHigh : 0.00
temperatureLow : 1022.10

NTP response time was : 65 ms
Time since last sync is: 6.34 s
Received NTP UTC time : 21:09:29
****** end of clip *******

**Comment by Bodmer** [comment]
To clarify, it is the output of this[ serial output only test sketch](https://github.com/Bodmer/DarkSkyWeather/tree/master/examples/My_DarkSkyWeather_Test) that I would like you to check.

**Comment by fixyourlan** [comment]
![darksky screen capt (2)](https://user-images.githubusercontent.com/6878048/70851545-15376d80-1e5c-11ea-8906-a8012879b5b8.JPG)

**Comment by fixyourlan** [comment]
Connected

Requesting weather information from DarkSky.net... Sending GET request to api.darksky.net...
X-Forecast-API-Calls: 107

Header end found
Parsing JSON

Done in 1805 ms

Weather from Dark Sky

############### Current weather ###############

Current time             : Sat Dec 14 16:54:12 2019
Current summary          : Clear
Current icon             : clear-day
Current precipInten      : 0.00
Current precipType       : none
Current precipProbability: 0
Current temperature      : 65.65
Current humidity         : 40
Current pressure         : 1011.30
Current wind speed       : 2.42
Current wind gust        : 5.09
Current wind dirn        : 121

############### Minutely weather  ###############

Overall minutely summary : Clear for the hour.
Minutely summary   Time               : Sat Dec 14 16:54:00 2019
precipIntensity    : 0.00
precipProbability  : 0

Minutely summary   Time               : Sat Dec 14 16:55:00 2019
precipIntensity    : 0.00
precipProbability  : 0

Minutely summary   Time               : Sat Dec 14 16:56:00 2019
precipIntensity    : 0.00
precipProbability  : 0

Minutely summary   Time               : Sat Dec 14 16:57:00 2019
precipIntensity    : 0.00
precipProbability  : 0

Minutely summary   Time               : Sat Dec 14 16:58:00 2019
precipIntensity    : 0.00
precipProbability  : 0

############### Hourly weather  ###############

Overall hourly summary : Clear throughout the day.
Hourly summary   0 : Clear
Time               : Sat Dec 14 16:00:00 2019
precipIntensity    : 0.00
precipProbability  : 0
precipType         : 11
precipAccumulation : 0.00
temperature        : 59.62
pressure           : 1012.00
cloudCover         : 0

Hourly summary   1 : Clear
Time               : Sat Dec 14 17:00:00 2019
precipIntensity    : 0.00
precipProbability  : 1
precipType         : 1
precipAccumulation : 0.00
temperature        : 66.24
pressure           : 1011.20
cloudCover         : 0

###############  Daily weather  ###############

Daily summary     : No precipitation throughout the week.

Daily summary   0 : Clear throughout the day.
time              : Sat Dec 14 06:00:00 2019
Icon              : clear-day
sunriseTime       : Sat Dec 14 13:22:00 2019
sunsetTime        : Sat Dec 14 23:38:00 2019
Moon phase        : 60
precipIntensity   : 0.00
precipProbability : 1
precipType        : 1
precipAccumulation: 0.00
temperatureHigh   : 79.96
temperatureLow    : 50.72
humidity          : 52
pressure          : 1009.70
windSpeed         : 4.00
windGust          : 13.43
windBearing       : 143
cloudCover        : 1

Daily summary   1 : Partly cloudy throughout the day.
time              : Sun Dec 15 06:00:00 2019
Icon              : partly-cloudy-day
sunriseTime       : Sun Dec 15 13:23:00 2019
sunsetTime        : Sun Dec 15 23:39:00 2019
Moon phase        : 64
precipIntensity   : 0.00
precipProbability : 9
precipType        : 1
precipAccumulation: 0.00
temperatureHigh   : 75.14
temperatureLow    : 60.42
humidity          : 81
pressure          : 1008.80
windSpeed         : 4.45
windGust          : 16.61
windBearing       : 173
cloudCover        : 24

**Comment by Bodmer** [comment]
The data with the test program looks good but this is a small subset.

If you run the original test program with the full data sets enabled do you see any corruption?

**Comment by fixyourlan** [comment]
Yes the output I sent you twice shows the corruption at day 2 summary. Look at listing. I have notes in listing where it begins. The screen shot of my display show how it will not display day 2 through 5. This happens even when using random locations. So it is not the data for this location,  it happens the same for 2 different types of esp8266 boards and 2 different displays!

Jim Bazar

> On Dec 14, 2019, at 2:22 PM, Bodmer <notifications@github.com> wrote:
> 

﻿
The data with the test program looks good but this is a small subset.

If you run the original test program with the full data sets enabled do you see any corruption?

**Comment by fixyourlan** [comment]
I finally found the place i had changed the max_dqys to 2 back when trying to  troubleshoot the first problem.  working ok now, sorry for the trouble, I swore i had checked all the locations where it was set and even searched the whole arduino library for that define and didn't find it in all the files i had checked.

**Comment by Bodmer** [comment]
Just logged in to ask you to check if the full [data sets are enabled here](https://github.com/Bodmer/DarkSkyWeather/blob/master/User_Setup.h#L9-L15). But I see you have it sorted and working, which is great to hear.

I think the issues you had with SPIFFS are down to a significant change made by the ESP8266 board package development team - essentially the older ESP8266 board packages are not compatible with the new IDE SPIFFS upload tool. Hope the weather if good for you!

**Comment by fixyourlan** [comment]
All is good now, spiffs working with both me esp8266 boards using latest version in boards manager!  The only thing I see wrong is the pressure is in millibars but says ‘in’ after it. I can just do the math on it to convert it to inches,  I have the formula in another program I wrote before for the bme280. I will be adding one onto my display to get inside sensor measurements along with a networked outside wireless solar charged station sending data to the display. Your examples are a big start to getting the dark sky data and forecast going for it. Thanks for your help. I’ll send you a link to my project when I publish it on github later!

Jim Bazar

> On Dec 14, 2019, at 4:48 PM, Bodmer <notifications@github.com> wrote:
> 

﻿
Just logged in to ask you to check if the full data sets are enabled here. But I see you have it sorted and working, which is great to hear.

I think the issues you had with SPIFFS are down to a significant change made by the ESP8266 board package development team - essentially the older ESP8266 board packages are not compatible with the new IDE SPIFFS upload tool. Hope the weather if good for you!

**Comment by Bodmer** [comment]
Looking forward to seeing your project.
