### ISSUE TITLE
Apple has purchased Dark Sky and is shutting down the API

### ISSUE THREAD

**Issue by tinohager** [Bodmer/DarkSkyWeather#28]
Apple has purchased Dark Sky and is shutting down the API.
The API will continue to function through the end of 2021.
[More Informations](https://blog.darksky.net/)

**Comment by Bodmer** [comment]
Doh!

Thanks for letting me know. I will probably swap to OpenWeatherMap or Yahoo weather...

**Comment by MikeA1s** [comment]
I just got the email too...too bad. That's the thing with free API's I guess.

**Comment by Fredy-1** [comment]
Hy!

This is a solution https://openweathermap.org/darksky-openweather?fbclid=IwAR1FfDOH7wgtAnGJRfi0K04Qi6mGh7lYmm5s0m-RrfgfXY4R6-P4DcPEykk

Is there a chance you can make a library with this one call API? (it's totaly free for 1000 calls/day or 60 calls/min)
https://openweathermap.org/api/one-call-api

**Comment by Bodmer** [comment]
Thanks.

I have created a new library that fetches weather from OpenWeather. Copy here:
https://github.com/Bodmer/OpenWeather

**Comment by MikeA1s** [comment]
404 page not found?

**Comment by Bodmer** [comment]
Ahh, it was private. It is not public. Thanks!

**Comment by Bodmer** [comment]
It is now public and should be accessible.

**Comment by MikeA1s** [comment]
awesome will upload sketch over the weekend and try...many thanks.

**Comment by Fredy-1** [comment]
Thank you Bodmer! You were fast. Perfect!
