### ISSUE TITLE
TFT example does not compile

### ISSUE THREAD

**Issue by MarcFinns** [Bodmer/DarkSkyWeather#3]
Hi Bodmer, I just tried the latest TFT example but it does not compile.
The offending line:
DS_Weather dsw; // Weather forecast library instance
error: cannot declare variable 'dsw' to be of abstract type 'DS_Weather'

**Comment by Bodmer** [comment]
The weather class has been renamed so the library needs too be replaced entirely. 

Development has stalled while I clean/reinstall the IDE environment and board support packages. The Arduino IDE (1.8.7) seems to have partially trashed something as I am getting all sorts of non existant errors reported in random blank lines!  I have 1.8.5 installed also and that has suddenly got upset as well with anything ESP8266 related. :-(

Hopefully I will have time get it sorted later today.

**Comment by MarcFinns** [comment]
Haven’t upgraded recently, so luckily I don’t have it!
No rush, I just wanted to let you know that the repository appear to be inconsistent. Thanks!

**Comment by Bodmer** [comment]
I have updated the repository so all should be good apart from an new issue with the ESP8266 not working with an NTP server. I will raise an issue on this.

**Comment by MarcFinns** [comment]
Hi Bodmer, i got the latest and have a compile error. offending line below. some file missing?
TFT_eSPI_weather_v4:55:77: error: JSON_Decoder.h: No such file or directory
 #include <JSON_Decoder.h> // https://github.com/Bodmer/json-streaming-parser                                     
compilation terminated.
exit status 1
JSON_Decoder.h: No such file or directory

**Comment by Bodmer** [comment]
Ah, you need this version of the JSON library:
https://github.com/Bodmer/JSON_Decoder

I will update the link in the comment, I thought I had weeded those out!

**Comment by Bodmer** [comment]
Fixed
