### ISSUE TITLE
Enhancement request, Night icons showing during the forecast.

### ISSUE THREAD

**Issue by SWEUSPeter** [Bodmer/DarkSkyWeather#7]
Hi,

The daily forecast is showing night icons when the day is clear. Per DarkSky API that's because of the following;

_Our system is presently very simple: it finds the “worst” weather condition that will happen during the day (4AM to 4AM), and uses the icon for it. The only case where a daily icon will show a *-night value is partly-cloudy-night, and this is done to match the daily summary text. We already have intentions to change this behavior, because it is confusing.
In the meantime, you can assume that if partly-cloudy-night is the worst weather condition that was found, that it was clear during the day. So you can just treat partly-cloudy-night as an alias for clear-day._

Until it gets addressed could this be added as an enhancement to your code?

Thank you,

Peter

**Comment by Bodmer** [comment]
You can change the behavior by [editing this line](https://github.com/Bodmer/DarkSkyWeather/blob/master/DarkSkyWeather.h#L100) in your copy of the "DarkSkyWeather.h" library file, just change -night" to -day" in two places

This works because this is a list of icon file names that are used.

**Comment by Bodmer** [comment]
Forgot to say: I will add a DAY_ICONS_ONLY option at some point if the DarkSky team do not fix it.

**Comment by Bodmer** [comment]
Change made to sketch.
