### ISSUE TITLE
Forecast icon not updating for 4th day from Midnight to 9 am 

### ISSUE THREAD

**Issue by gcharles81** [Bodmer/DarkSkyWeather#8]
Hello and thanks for the great library 

I have an issue with forecast icon not updating for 4th day from Midnight to 9 am , but if i activate serial data serial is printing the data for all 5 days requested defined with #define MAX_DAYS 5

I am using TIMEZONE euCET , might be this is the issue and below is the log from the serial 

NTP response time was : 144 ms
Time since last sync is: 3.26 s
Received NTP UTC time : 6:39:48

Sending GET request to api.darksky.net...
X-Forecast-API-Calls: 39

Header end found

Parsing JSON

Done in 1590 ms

Weather from Dark Sky

############### Current weather ###############

time               : Jan 8 07:39
summary            : Light Rain
icon               : 1
temperature        : 2.21
humidity           : 89
pressure           : 1024.47
wind speed         : 3.18
wind dirn          : 222
cloudCover         : 85

###############  Daily weather  ###############

 Overall summary     : Mixed precipitation today through Monday, with high temperatures bottoming out at 0°C on Thursday.

Day summary   0    : Snow (2–5 cm.) starting in the evening.
time               : Jan 8 00:00
icon               : 3
sunriseTime        : Jan 8 08:12
sunsetTime         : Jan 8 16:54
Moon phase         : 8
temperatureHigh    : 4.65
temperatureLow     : 1.08

Day summary   1    : Snow (9–17 cm.) throughout the day.
time               : Jan 9 00:00
icon               : 3
sunriseTime        : Jan 9 08:12
sunsetTime         : Jan 9 16:55
Moon phase         : 11
temperatureHigh    : 1.42
temperatureLow     : -1.89

Day summary   2    : Snow (3–9 cm.) until evening.
time               : Jan 10 00:00
icon               : 3
sunriseTime        : Jan 10 08:12
sunsetTime         : Jan 10 16:57
Moon phase         : 14
temperatureHigh    : -0.44
temperatureLow     : -2.67

Day summary   3    : Mostly cloudy throughout the day.
time               : Jan 11 00:00
icon               : 6
sunriseTime        : Jan 11 08:11
sunsetTime         : Jan 11 16:58
Moon phase         : 17
temperatureHigh    : -1.30
temperatureLow     : -2.32

Day summary   4    : Light snow (< 1 cm.) overnight.
time               : Jan 12 00:00
icon               : 3
sunriseTime        : Jan 12 08:11
sunsetTime         : Jan 12 16:59
Moon phase         : 20
temperatureHigh    : 3.29
temperatureLow     : 3.18

**Comment by Bodmer** [comment]
Thanks for reporting this, I will investigate.

**Comment by Bodmer** [comment]
I have made [the change here](https://github.com/Bodmer/DarkSkyWeather/blob/master/examples/TFT_eSPI_weather/TFT_eSPI_weather.ino#L413-L414).

This should fix the problem.  I do not remember why I put the while() line in! There may be a case where this is needed, I will run the sketch for a few days to see what happens.

**Comment by gcharles81** [comment]
Thanks very much for the prompt fix I will try tonight ans give you feedback , so far it seems it is working fine.
Thanks

**Comment by gcharles81** [comment]
Thanks change confirmed working fine
