### ISSUE TITLE
debug level

### ISSUE THREAD

**Issue by anajantech** [Bodmer/DarkSkyWeather#9]
Is it possible to increase debug level on darkskyweather?  Running bare bones example I can see it connect, request weather, then … fail.  Wondering if it got to make a request, or if the request failed on my key.  Not sure where to start a divide with such a small example.

**Comment by Bodmer** [comment]
You can see the response header in the Serial Monitor window if you u[ncomment this line](https://github.com/Bodmer/DarkSkyWeather/blob/master/User_Setup.h#L29).

**Comment by anajantech** [comment]
I like the options in the user_setup. This is probably something simple on my side since I'm sick and I'm tired, but I cannot get either darksky examples to work atm.  The key worked when using it with a browser.  Will try again after a break and hopefully see what I'm doing wrong.
